"""Closed, statically declared REST operation registry.

Every typed operation this extension can dispatch is declared here as a literal
row. Nothing is derived from ``/wp-json/``, ``OPTIONS``, installed plugins, or
site configuration: an operation that is not in this table cannot be routed, and
a namespace, method, or route that is not carried by a row in this table is
never built into a request. ``contracts/rest_coverage.yaml`` is the published
mirror of this table and is kept in exact parity by the extension-owned tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

_PATH_SETTINGS = "/settings"

WORDPRESS = "wordpress"
WOOCOMMERCE = "woocommerce"

WORDPRESS_NAMESPACE = "wp/v2"
WOOCOMMERCE_NAMESPACE = "wc/v3"
SUPPORTED_NAMESPACES: frozenset[str] = frozenset({WORDPRESS_NAMESPACE, WOOCOMMERCE_NAMESPACE})
SUPPORTED_METHODS: frozenset[str] = frozenset({"GET", "POST", "PUT"})

WORDPRESS_DOC_BASE = "https://developer.wordpress.org/rest-api/reference/"
WOOCOMMERCE_DOC_BASE = "https://developer.woocommerce.com/docs/apis/rest-api/v3/"

READ_SHAPES: frozenset[str] = frozenset({"list", "get", "read_post"})
EFFECT_SHAPES: frozenset[str] = frozenset({"create", "update", "batch", "action", "media_create"})
SHAPES: frozenset[str] = READ_SHAPES | EFFECT_SHAPES

PATH_PARAM_KINDS: frozenset[str] = frozenset({"integer", "slug", "namespaced_slug", "plugin_file"})


@dataclass(frozen=True)
class Operation:
    """One typed, statically declared native REST operation."""

    operation_id: str
    provider: str
    resource: str
    namespace: str
    route: str
    method: str
    shape: str
    display_name: str
    doc_slug: str
    path_params: tuple[tuple[str, str], ...] = ()

    @property
    def route_pattern(self) -> str:
        return f"/wp-json/{self.namespace}{self.route}"

    @property
    def doc_url(self) -> str:
        base = WORDPRESS_DOC_BASE if self.provider == WORDPRESS else WOOCOMMERCE_DOC_BASE
        return f"{base}{self.doc_slug}/"

    @property
    def operation_kind(self) -> str:
        return "source" if self.shape in READ_SHAPES else "action"

    @property
    def has_external_effect(self) -> bool:
        return self.shape in EFFECT_SHAPES

    @property
    def category(self) -> str:
        return "cms" if self.provider == WORDPRESS else "ecommerce"

    @property
    def effect_kind(self) -> str:
        return f"{self.provider}_{self.resource}_{self.shape}"

    @property
    def channel(self) -> str:
        return "wordpress_rest" if self.provider == WORDPRESS else "woocommerce_rest"


def _wp(
    operation_id: str,
    resource: str,
    route: str,
    method: str,
    shape: str,
    display_name: str,
    doc_slug: str,
    path_params: tuple[tuple[str, str], ...] = (),
) -> Operation:
    return Operation(
        operation_id=operation_id,
        provider=WORDPRESS,
        resource=resource,
        namespace=WORDPRESS_NAMESPACE,
        route=route,
        method=method,
        shape=shape,
        display_name=display_name,
        doc_slug=doc_slug,
        path_params=path_params,
    )


def _wc(
    operation_id: str,
    resource: str,
    route: str,
    method: str,
    shape: str,
    display_name: str,
    doc_slug: str,
    path_params: tuple[tuple[str, str], ...] = (),
) -> Operation:
    return Operation(
        operation_id=operation_id,
        provider=WOOCOMMERCE,
        resource=resource,
        namespace=WOOCOMMERCE_NAMESPACE,
        route=route,
        method=method,
        shape=shape,
        display_name=display_name,
        doc_slug=doc_slug,
        path_params=path_params,
    )


_ID = (("id", "integer"),)
_PARENT = (("parent", "integer"),)
_PARENT_ID = (("parent", "integer"), ("id", "integer"))

WORDPRESS_OPERATIONS: tuple[Operation, ...] = (
    # Posts
    _wp("wp_list_posts", "posts", "/posts", "GET", "list", "List WordPress posts", "posts"),
    _wp("wp_create_post", "posts", "/posts", "POST", "create", "Create WordPress post", "posts"),
    _wp("wp_get_post", "posts", "/posts/{id}", "GET", "get", "Get WordPress post", "posts", _ID),
    _wp(
        "wp_update_post",
        "posts",
        "/posts/{id}",
        "POST",
        "update",
        "Update WordPress post",
        "posts",
        _ID,
    ),
    # Post revisions and autosaves
    _wp(
        "wp_list_post_revisions",
        "post_revisions",
        "/posts/{parent}/revisions",
        "GET",
        "list",
        "List WordPress post revisions",
        "post-revisions",
        _PARENT,
    ),
    _wp(
        "wp_get_post_revision",
        "post_revisions",
        "/posts/{parent}/revisions/{id}",
        "GET",
        "get",
        "Get WordPress post revision",
        "post-revisions",
        _PARENT_ID,
    ),
    _wp(
        "wp_list_post_autosaves",
        "post_revisions",
        "/posts/{id}/autosaves",
        "GET",
        "list",
        "List WordPress post autosaves",
        "post-revisions",
        _ID,
    ),
    _wp(
        "wp_create_post_autosave",
        "post_revisions",
        "/posts/{id}/autosaves",
        "POST",
        "create",
        "Create WordPress post autosave",
        "post-revisions",
        _ID,
    ),
    _wp(
        "wp_get_post_autosave",
        "post_revisions",
        "/posts/{parent}/autosaves/{id}",
        "GET",
        "get",
        "Get WordPress post autosave",
        "post-revisions",
        _PARENT_ID,
    ),
    # Pages
    _wp("wp_list_pages", "pages", "/pages", "GET", "list", "List WordPress pages", "pages"),
    _wp("wp_create_page", "pages", "/pages", "POST", "create", "Create WordPress page", "pages"),
    _wp("wp_get_page", "pages", "/pages/{id}", "GET", "get", "Get WordPress page", "pages", _ID),
    _wp(
        "wp_update_page",
        "pages",
        "/pages/{id}",
        "POST",
        "update",
        "Update WordPress page",
        "pages",
        _ID,
    ),
    # Page revisions and autosaves
    _wp(
        "wp_list_page_revisions",
        "page_revisions",
        "/pages/{parent}/revisions",
        "GET",
        "list",
        "List WordPress page revisions",
        "page-revisions",
        _PARENT,
    ),
    _wp(
        "wp_get_page_revision",
        "page_revisions",
        "/pages/{parent}/revisions/{id}",
        "GET",
        "get",
        "Get WordPress page revision",
        "page-revisions",
        _PARENT_ID,
    ),
    _wp(
        "wp_list_page_autosaves",
        "page_revisions",
        "/pages/{id}/autosaves",
        "GET",
        "list",
        "List WordPress page autosaves",
        "page-revisions",
        _ID,
    ),
    _wp(
        "wp_create_page_autosave",
        "page_revisions",
        "/pages/{id}/autosaves",
        "POST",
        "create",
        "Create WordPress page autosave",
        "page-revisions",
        _ID,
    ),
    _wp(
        "wp_get_page_autosave",
        "page_revisions",
        "/pages/{parent}/autosaves/{id}",
        "GET",
        "get",
        "Get WordPress page autosave",
        "page-revisions",
        _PARENT_ID,
    ),
    # Media
    _wp("wp_list_media", "media", "/media", "GET", "list", "List WordPress media", "media"),
    _wp(
        "wp_create_media",
        "media",
        "/media",
        "POST",
        "media_create",
        "Upload WordPress media",
        "media",
    ),
    _wp(
        "wp_get_media",
        "media",
        "/media/{id}",
        "GET",
        "get",
        "Get WordPress media item",
        "media",
        _ID,
    ),
    _wp(
        "wp_update_media",
        "media",
        "/media/{id}",
        "POST",
        "update",
        "Update WordPress media item",
        "media",
        _ID,
    ),
    # Comments
    _wp(
        "wp_list_comments",
        "comments",
        "/comments",
        "GET",
        "list",
        "List WordPress comments",
        "comments",
    ),
    _wp(
        "wp_create_comment",
        "comments",
        "/comments",
        "POST",
        "create",
        "Create WordPress comment",
        "comments",
    ),
    _wp(
        "wp_get_comment",
        "comments",
        "/comments/{id}",
        "GET",
        "get",
        "Get WordPress comment",
        "comments",
        _ID,
    ),
    _wp(
        "wp_update_comment",
        "comments",
        "/comments/{id}",
        "POST",
        "update",
        "Update WordPress comment",
        "comments",
        _ID,
    ),
    # Categories
    _wp(
        "wp_list_categories",
        "categories",
        "/categories",
        "GET",
        "list",
        "List WordPress categories",
        "categories",
    ),
    _wp(
        "wp_create_category",
        "categories",
        "/categories",
        "POST",
        "create",
        "Create WordPress category",
        "categories",
    ),
    _wp(
        "wp_get_category",
        "categories",
        "/categories/{id}",
        "GET",
        "get",
        "Get WordPress category",
        "categories",
        _ID,
    ),
    _wp(
        "wp_update_category",
        "categories",
        "/categories/{id}",
        "POST",
        "update",
        "Update WordPress category",
        "categories",
        _ID,
    ),
    # Tags
    _wp("wp_list_tags", "tags", "/tags", "GET", "list", "List WordPress tags", "tags"),
    _wp("wp_create_tag", "tags", "/tags", "POST", "create", "Create WordPress tag", "tags"),
    _wp("wp_get_tag", "tags", "/tags/{id}", "GET", "get", "Get WordPress tag", "tags", _ID),
    _wp(
        "wp_update_tag", "tags", "/tags/{id}", "POST", "update", "Update WordPress tag", "tags", _ID
    ),
    # Taxonomies
    _wp(
        "wp_get_taxonomies",
        "taxonomies",
        "/taxonomies",
        "GET",
        "get",
        "Get WordPress taxonomies",
        "taxonomies",
    ),
    _wp(
        "wp_get_taxonomy",
        "taxonomies",
        "/taxonomies/{taxonomy}",
        "GET",
        "get",
        "Get WordPress taxonomy",
        "taxonomies",
        (("taxonomy", "slug"),),
    ),
    # Users
    # Users are read-only here: creating or changing an account is administration
    # rather than automation, and the excluded routes stay visible in coverage.
    _wp("wp_list_users", "users", "/users", "GET", "list", "List WordPress users", "users"),
    _wp("wp_get_user", "users", "/users/{id}", "GET", "get", "Get WordPress user", "users", _ID),
    _wp(
        "wp_get_current_user",
        "users",
        "/users/me",
        "GET",
        "get",
        "Get current WordPress user",
        "users",
    ),
    # Post types and statuses
    _wp(
        "wp_get_post_types",
        "post_types",
        "/types",
        "GET",
        "get",
        "Get WordPress post types",
        "post-types",
    ),
    _wp(
        "wp_get_post_type",
        "post_types",
        "/types/{type}",
        "GET",
        "get",
        "Get WordPress post type",
        "post-types",
        (("type", "slug"),),
    ),
    _wp(
        "wp_get_post_statuses",
        "post_statuses",
        "/statuses",
        "GET",
        "get",
        "Get WordPress post statuses",
        "post-statuses",
    ),
    _wp(
        "wp_get_post_status",
        "post_statuses",
        "/statuses/{status}",
        "GET",
        "get",
        "Get WordPress post status",
        "post-statuses",
        (("status", "slug"),),
    ),
    # Site settings
    _wp(
        "wp_get_settings",
        "settings",
        _PATH_SETTINGS,
        "GET",
        "get",
        "Get WordPress site settings",
        "settings",
    ),
    _wp(
        "wp_update_settings",
        "settings",
        _PATH_SETTINGS,
        "POST",
        "update",
        "Update WordPress site settings",
        "settings",
    ),
    # Themes (read-only)
    _wp("wp_list_themes", "themes", "/themes", "GET", "list", "List WordPress themes", "themes"),
    _wp(
        "wp_get_theme",
        "themes",
        "/themes/{stylesheet}",
        "GET",
        "get",
        "Get WordPress theme",
        "themes",
        (("stylesheet", "plugin_file"),),
    ),
    # Search
    _wp(
        "wp_search",
        "search",
        "/search",
        "GET",
        "list",
        "Search WordPress content",
        "search-results",
    ),
    # Block types
    _wp(
        "wp_list_block_types",
        "block_types",
        "/block-types",
        "GET",
        "list",
        "List WordPress block types",
        "block-types",
    ),
    _wp(
        "wp_list_namespace_block_types",
        "block_types",
        "/block-types/{namespace}",
        "GET",
        "list",
        "List WordPress block types in a namespace",
        "block-types",
        (("namespace", "slug"),),
    ),
    _wp(
        "wp_get_block_type",
        "block_types",
        "/block-types/{namespace}/{name}",
        "GET",
        "get",
        "Get WordPress block type",
        "block-types",
        (("namespace", "slug"), ("name", "slug")),
    ),
    # Editor blocks
    _wp(
        "wp_list_blocks",
        "blocks",
        "/blocks",
        "GET",
        "list",
        "List WordPress editor blocks",
        "blocks",
    ),
    _wp(
        "wp_create_block",
        "blocks",
        "/blocks",
        "POST",
        "create",
        "Create WordPress editor block",
        "blocks",
    ),
    _wp(
        "wp_get_block",
        "blocks",
        "/blocks/{id}",
        "GET",
        "get",
        "Get WordPress editor block",
        "blocks",
        _ID,
    ),
    _wp(
        "wp_update_block",
        "blocks",
        "/blocks/{id}",
        "POST",
        "update",
        "Update WordPress editor block",
        "blocks",
        _ID,
    ),
    # Block revisions and autosaves
    _wp(
        "wp_list_block_revisions",
        "block_revisions",
        "/blocks/{parent}/revisions",
        "GET",
        "list",
        "List WordPress block revisions",
        "block-revisions",
        _PARENT,
    ),
    _wp(
        "wp_get_block_revision",
        "block_revisions",
        "/blocks/{parent}/revisions/{id}",
        "GET",
        "get",
        "Get WordPress block revision",
        "block-revisions",
        _PARENT_ID,
    ),
    _wp(
        "wp_list_block_autosaves",
        "block_revisions",
        "/blocks/{id}/autosaves",
        "GET",
        "list",
        "List WordPress block autosaves",
        "block-revisions",
        _ID,
    ),
    _wp(
        "wp_create_block_autosave",
        "block_revisions",
        "/blocks/{id}/autosaves",
        "POST",
        "create",
        "Create WordPress block autosave",
        "block-revisions",
        _ID,
    ),
    _wp(
        "wp_get_block_autosave",
        "block_revisions",
        "/blocks/{parent}/autosaves/{id}",
        "GET",
        "get",
        "Get WordPress block autosave",
        "block-revisions",
        _PARENT_ID,
    ),
    # Block directory, patterns, and rendering
    _wp(
        "wp_search_block_directory",
        "block_directory_items",
        "/block-directory/search",
        "GET",
        "list",
        "Search the WordPress block directory",
        "block-directory-items",
    ),
    _wp(
        "wp_list_block_patterns",
        "block_patterns",
        "/block-patterns/patterns",
        "GET",
        "list",
        "List WordPress block patterns",
        "block-patterns",
    ),
    _wp(
        "wp_list_block_pattern_categories",
        "block_pattern_categories",
        "/block-patterns/categories",
        "GET",
        "list",
        "List WordPress block pattern categories",
        "block-pattern-categories",
    ),
    _wp(
        "wp_list_pattern_directory_patterns",
        "pattern_directory_items",
        "/pattern-directory/patterns",
        "GET",
        "list",
        "List WordPress pattern directory items",
        "pattern-directory-items",
    ),
    _wp(
        "wp_render_block",
        "rendered_blocks",
        "/block-renderer/{name}",
        "POST",
        "read_post",
        "Render a WordPress block",
        "rendered-blocks",
        (("name", "namespaced_slug"),),
    ),
    # Menu locations
    _wp(
        "wp_get_menu_locations",
        "menu_locations",
        "/menu-locations",
        "GET",
        "get",
        "Get WordPress menu locations",
        "menu-locations",
    ),
    _wp(
        "wp_get_menu_location",
        "menu_locations",
        "/menu-locations/{location}",
        "GET",
        "get",
        "Get WordPress menu location",
        "menu-locations",
        (("location", "slug"),),
    ),
    # Sidebars
    _wp(
        "wp_list_sidebars",
        "sidebars",
        "/sidebars",
        "GET",
        "list",
        "List WordPress sidebars",
        "sidebars",
    ),
    _wp(
        "wp_get_sidebar",
        "sidebars",
        "/sidebars/{id}",
        "GET",
        "get",
        "Get WordPress sidebar",
        "sidebars",
        (("id", "slug"),),
    ),
    _wp(
        "wp_update_sidebar",
        "sidebars",
        "/sidebars/{id}",
        "POST",
        "update",
        "Update WordPress sidebar",
        "sidebars",
        (("id", "slug"),),
    ),
    # Widget types
    _wp(
        "wp_list_widget_types",
        "widget_types",
        "/widget-types",
        "GET",
        "list",
        "List WordPress widget types",
        "widget-types",
    ),
    _wp(
        "wp_get_widget_type",
        "widget_types",
        "/widget-types/{id}",
        "GET",
        "get",
        "Get WordPress widget type",
        "widget-types",
        (("id", "slug"),),
    ),
    # Widgets
    _wp(
        "wp_list_widgets", "widgets", "/widgets", "GET", "list", "List WordPress widgets", "widgets"
    ),
    _wp(
        "wp_create_widget",
        "widgets",
        "/widgets",
        "POST",
        "create",
        "Create WordPress widget",
        "widgets",
    ),
    _wp(
        "wp_get_widget",
        "widgets",
        "/widgets/{id}",
        "GET",
        "get",
        "Get WordPress widget",
        "widgets",
        (("id", "slug"),),
    ),
    _wp(
        "wp_update_widget",
        "widgets",
        "/widgets/{id}",
        "POST",
        "update",
        "Update WordPress widget",
        "widgets",
        (("id", "slug"),),
    ),
    # Plugins (read-only)
    _wp(
        "wp_list_plugins", "plugins", "/plugins", "GET", "list", "List WordPress plugins", "plugins"
    ),
    _wp(
        "wp_get_plugin",
        "plugins",
        "/plugins/{plugin}",
        "GET",
        "get",
        "Get WordPress plugin",
        "plugins",
        (("plugin", "plugin_file"),),
    ),
)

WOOCOMMERCE_OPERATIONS: tuple[Operation, ...] = (
    # Coupons
    _wc(
        "wc_list_coupons",
        "coupons",
        "/coupons",
        "GET",
        "list",
        "List WooCommerce coupons",
        "coupons",
    ),
    _wc(
        "wc_create_coupon",
        "coupons",
        "/coupons",
        "POST",
        "create",
        "Create WooCommerce coupon",
        "coupons",
    ),
    _wc(
        "wc_get_coupon",
        "coupons",
        "/coupons/{id}",
        "GET",
        "get",
        "Get WooCommerce coupon",
        "coupons",
        _ID,
    ),
    _wc(
        "wc_update_coupon",
        "coupons",
        "/coupons/{id}",
        "PUT",
        "update",
        "Update WooCommerce coupon",
        "coupons",
        _ID,
    ),
    _wc(
        "wc_batch_coupons",
        "coupons",
        "/coupons/batch",
        "POST",
        "batch",
        "Batch create or update WooCommerce coupons",
        "coupons",
    ),
    # Customers
    _wc(
        "wc_list_customers",
        "customers",
        "/customers",
        "GET",
        "list",
        "List WooCommerce customers",
        "customers",
    ),
    _wc(
        "wc_create_customer",
        "customers",
        "/customers",
        "POST",
        "create",
        "Create WooCommerce customer",
        "customers",
    ),
    _wc(
        "wc_get_customer",
        "customers",
        "/customers/{id}",
        "GET",
        "get",
        "Get WooCommerce customer",
        "customers",
        _ID,
    ),
    _wc(
        "wc_update_customer",
        "customers",
        "/customers/{id}",
        "PUT",
        "update",
        "Update WooCommerce customer",
        "customers",
        _ID,
    ),
    _wc(
        "wc_batch_customers",
        "customers",
        "/customers/batch",
        "POST",
        "batch",
        "Batch create or update WooCommerce customers",
        "customers",
    ),
    _wc(
        "wc_list_customer_downloads",
        "customers",
        "/customers/{id}/downloads",
        "GET",
        "list",
        "List WooCommerce customer downloads",
        "customers",
        _ID,
    ),
    # Orders
    _wc("wc_list_orders", "orders", "/orders", "GET", "list", "List WooCommerce orders", "orders"),
    _wc(
        "wc_create_order",
        "orders",
        "/orders",
        "POST",
        "create",
        "Create WooCommerce order",
        "orders",
    ),
    _wc(
        "wc_get_order",
        "orders",
        "/orders/{id}",
        "GET",
        "get",
        "Get WooCommerce order",
        "orders",
        _ID,
    ),
    _wc(
        "wc_update_order",
        "orders",
        "/orders/{id}",
        "PUT",
        "update",
        "Update WooCommerce order",
        "orders",
        _ID,
    ),
    _wc(
        "wc_batch_orders",
        "orders",
        "/orders/batch",
        "POST",
        "batch",
        "Batch create or update WooCommerce orders",
        "orders",
    ),
    # Order actions
    _wc(
        "wc_list_order_email_templates",
        "order_actions",
        "/orders/{id}/actions/email_templates",
        "GET",
        "list",
        "List WooCommerce order email templates",
        "order-actions",
        _ID,
    ),
    _wc(
        "wc_send_order_details",
        "order_actions",
        "/orders/{id}/actions/send_order_details",
        "POST",
        "action",
        "Send WooCommerce order details",
        "order-actions",
        _ID,
    ),
    _wc(
        "wc_send_order_email",
        "order_actions",
        "/orders/{id}/actions/send_email",
        "POST",
        "action",
        "Send WooCommerce order email",
        "order-actions",
        _ID,
    ),
    # Order notes
    _wc(
        "wc_list_order_notes",
        "order_notes",
        "/orders/{id}/notes",
        "GET",
        "list",
        "List WooCommerce order notes",
        "order-notes",
        _ID,
    ),
    _wc(
        "wc_create_order_note",
        "order_notes",
        "/orders/{id}/notes",
        "POST",
        "create",
        "Create WooCommerce order note",
        "order-notes",
        _ID,
    ),
    _wc(
        "wc_get_order_note",
        "order_notes",
        "/orders/{id}/notes/{note_id}",
        "GET",
        "get",
        "Get WooCommerce order note",
        "order-notes",
        (("id", "integer"), ("note_id", "integer")),
    ),
    # Order refunds (read-only)
    _wc(
        "wc_list_order_refunds",
        "order_refunds",
        "/orders/{id}/refunds",
        "GET",
        "list",
        "List WooCommerce order refunds",
        "order-refunds",
        _ID,
    ),
    _wc(
        "wc_get_order_refund",
        "order_refunds",
        "/orders/{id}/refunds/{refund_id}",
        "GET",
        "get",
        "Get WooCommerce order refund",
        "order-refunds",
        (("id", "integer"), ("refund_id", "integer")),
    ),
    _wc(
        "wc_preview_order_refund",
        "order_refunds",
        "/orders/{id}/refunds/preview",
        "POST",
        "read_post",
        "Preview a WooCommerce order refund",
        "order-refunds",
        _ID,
    ),
    _wc(
        "wc_list_refunds",
        "refunds",
        "/refunds",
        "GET",
        "list",
        "List WooCommerce refunds",
        "refunds",
    ),
    # Products
    _wc(
        "wc_list_products",
        "products",
        "/products",
        "GET",
        "list",
        "List WooCommerce products",
        "products",
    ),
    _wc(
        "wc_create_product",
        "products",
        "/products",
        "POST",
        "create",
        "Create WooCommerce product",
        "products",
    ),
    _wc(
        "wc_get_product",
        "products",
        "/products/{id}",
        "GET",
        "get",
        "Get WooCommerce product",
        "products",
        _ID,
    ),
    _wc(
        "wc_update_product",
        "products",
        "/products/{id}",
        "PUT",
        "update",
        "Update WooCommerce product",
        "products",
        _ID,
    ),
    _wc(
        "wc_batch_products",
        "products",
        "/products/batch",
        "POST",
        "batch",
        "Batch create or update WooCommerce products",
        "products",
    ),
    _wc(
        "wc_duplicate_product",
        "products",
        "/products/{product_id}/duplicate",
        "POST",
        "action",
        "Duplicate WooCommerce product",
        "products",
        (("product_id", "integer"),),
    ),
    # Product variations
    _wc(
        "wc_list_product_variations",
        "product_variations",
        "/products/{product_id}/variations",
        "GET",
        "list",
        "List WooCommerce product variations",
        "product-variations",
        (("product_id", "integer"),),
    ),
    _wc(
        "wc_create_product_variation",
        "product_variations",
        "/products/{product_id}/variations",
        "POST",
        "create",
        "Create WooCommerce product variation",
        "product-variations",
        (("product_id", "integer"),),
    ),
    _wc(
        "wc_get_product_variation",
        "product_variations",
        "/products/{product_id}/variations/{id}",
        "GET",
        "get",
        "Get WooCommerce product variation",
        "product-variations",
        (("product_id", "integer"), ("id", "integer")),
    ),
    _wc(
        "wc_update_product_variation",
        "product_variations",
        "/products/{product_id}/variations/{id}",
        "PUT",
        "update",
        "Update WooCommerce product variation",
        "product-variations",
        (("product_id", "integer"), ("id", "integer")),
    ),
    _wc(
        "wc_batch_product_variations",
        "product_variations",
        "/products/{product_id}/variations/batch",
        "POST",
        "batch",
        "Batch create or update WooCommerce product variations",
        "product-variations",
        (("product_id", "integer"),),
    ),
    # Product attributes
    _wc(
        "wc_list_product_attributes",
        "product_attributes",
        "/products/attributes",
        "GET",
        "list",
        "List WooCommerce product attributes",
        "product-attributes",
    ),
    _wc(
        "wc_create_product_attribute",
        "product_attributes",
        "/products/attributes",
        "POST",
        "create",
        "Create WooCommerce product attribute",
        "product-attributes",
    ),
    _wc(
        "wc_get_product_attribute",
        "product_attributes",
        "/products/attributes/{id}",
        "GET",
        "get",
        "Get WooCommerce product attribute",
        "product-attributes",
        _ID,
    ),
    _wc(
        "wc_update_product_attribute",
        "product_attributes",
        "/products/attributes/{id}",
        "PUT",
        "update",
        "Update WooCommerce product attribute",
        "product-attributes",
        _ID,
    ),
    _wc(
        "wc_batch_product_attributes",
        "product_attributes",
        "/products/attributes/batch",
        "POST",
        "batch",
        "Batch create or update WooCommerce product attributes",
        "product-attributes",
    ),
    # Product attribute terms
    _wc(
        "wc_list_product_attribute_terms",
        "product_attribute_terms",
        "/products/attributes/{attribute_id}/terms",
        "GET",
        "list",
        "List WooCommerce product attribute terms",
        "product-attribute-terms",
        (("attribute_id", "integer"),),
    ),
    _wc(
        "wc_create_product_attribute_term",
        "product_attribute_terms",
        "/products/attributes/{attribute_id}/terms",
        "POST",
        "create",
        "Create WooCommerce product attribute term",
        "product-attribute-terms",
        (("attribute_id", "integer"),),
    ),
    _wc(
        "wc_get_product_attribute_term",
        "product_attribute_terms",
        "/products/attributes/{attribute_id}/terms/{id}",
        "GET",
        "get",
        "Get WooCommerce product attribute term",
        "product-attribute-terms",
        (("attribute_id", "integer"), ("id", "integer")),
    ),
    _wc(
        "wc_update_product_attribute_term",
        "product_attribute_terms",
        "/products/attributes/{attribute_id}/terms/{id}",
        "PUT",
        "update",
        "Update WooCommerce product attribute term",
        "product-attribute-terms",
        (("attribute_id", "integer"), ("id", "integer")),
    ),
    _wc(
        "wc_batch_product_attribute_terms",
        "product_attribute_terms",
        "/products/attributes/{attribute_id}/terms/batch",
        "POST",
        "batch",
        "Batch create or update WooCommerce product attribute terms",
        "product-attribute-terms",
        (("attribute_id", "integer"),),
    ),
    # Product categories
    _wc(
        "wc_list_product_categories",
        "product_categories",
        "/products/categories",
        "GET",
        "list",
        "List WooCommerce product categories",
        "product-categories",
    ),
    _wc(
        "wc_create_product_category",
        "product_categories",
        "/products/categories",
        "POST",
        "create",
        "Create WooCommerce product category",
        "product-categories",
    ),
    _wc(
        "wc_get_product_category",
        "product_categories",
        "/products/categories/{id}",
        "GET",
        "get",
        "Get WooCommerce product category",
        "product-categories",
        _ID,
    ),
    _wc(
        "wc_update_product_category",
        "product_categories",
        "/products/categories/{id}",
        "PUT",
        "update",
        "Update WooCommerce product category",
        "product-categories",
        _ID,
    ),
    _wc(
        "wc_batch_product_categories",
        "product_categories",
        "/products/categories/batch",
        "POST",
        "batch",
        "Batch create or update WooCommerce product categories",
        "product-categories",
    ),
    # Product custom-field names
    _wc(
        "wc_list_product_custom_field_names",
        "product_custom_fields",
        "/products/custom-fields/names",
        "GET",
        "list",
        "List WooCommerce product custom-field names",
        "product-custom-fields",
    ),
    # Product shipping classes
    _wc(
        "wc_list_product_shipping_classes",
        "product_shipping_classes",
        "/products/shipping_classes",
        "GET",
        "list",
        "List WooCommerce product shipping classes",
        "product-shipping-classes",
    ),
    _wc(
        "wc_create_product_shipping_class",
        "product_shipping_classes",
        "/products/shipping_classes",
        "POST",
        "create",
        "Create WooCommerce product shipping class",
        "product-shipping-classes",
    ),
    _wc(
        "wc_get_product_shipping_class",
        "product_shipping_classes",
        "/products/shipping_classes/{id}",
        "GET",
        "get",
        "Get WooCommerce product shipping class",
        "product-shipping-classes",
        _ID,
    ),
    _wc(
        "wc_update_product_shipping_class",
        "product_shipping_classes",
        "/products/shipping_classes/{id}",
        "PUT",
        "update",
        "Update WooCommerce product shipping class",
        "product-shipping-classes",
        _ID,
    ),
    _wc(
        "wc_batch_product_shipping_classes",
        "product_shipping_classes",
        "/products/shipping_classes/batch",
        "POST",
        "batch",
        "Batch create or update WooCommerce product shipping classes",
        "product-shipping-classes",
    ),
    # Product tags
    _wc(
        "wc_list_product_tags",
        "product_tags",
        "/products/tags",
        "GET",
        "list",
        "List WooCommerce product tags",
        "product-tags",
    ),
    _wc(
        "wc_create_product_tag",
        "product_tags",
        "/products/tags",
        "POST",
        "create",
        "Create WooCommerce product tag",
        "product-tags",
    ),
    _wc(
        "wc_get_product_tag",
        "product_tags",
        "/products/tags/{id}",
        "GET",
        "get",
        "Get WooCommerce product tag",
        "product-tags",
        _ID,
    ),
    _wc(
        "wc_update_product_tag",
        "product_tags",
        "/products/tags/{id}",
        "PUT",
        "update",
        "Update WooCommerce product tag",
        "product-tags",
        _ID,
    ),
    _wc(
        "wc_batch_product_tags",
        "product_tags",
        "/products/tags/batch",
        "POST",
        "batch",
        "Batch create or update WooCommerce product tags",
        "product-tags",
    ),
    # Product reviews
    _wc(
        "wc_list_product_reviews",
        "product_reviews",
        "/products/reviews",
        "GET",
        "list",
        "List WooCommerce product reviews",
        "product-reviews",
    ),
    _wc(
        "wc_create_product_review",
        "product_reviews",
        "/products/reviews",
        "POST",
        "create",
        "Create WooCommerce product review",
        "product-reviews",
    ),
    _wc(
        "wc_get_product_review",
        "product_reviews",
        "/products/reviews/{id}",
        "GET",
        "get",
        "Get WooCommerce product review",
        "product-reviews",
        _ID,
    ),
    _wc(
        "wc_update_product_review",
        "product_reviews",
        "/products/reviews/{id}",
        "PUT",
        "update",
        "Update WooCommerce product review",
        "product-reviews",
        _ID,
    ),
    _wc(
        "wc_batch_product_reviews",
        "product_reviews",
        "/products/reviews/batch",
        "POST",
        "batch",
        "Batch create or update WooCommerce product reviews",
        "product-reviews",
    ),
    # Reports
    _wc(
        "wc_list_reports",
        "reports",
        "/reports",
        "GET",
        "list",
        "List WooCommerce reports",
        "reports",
    ),
    _wc(
        "wc_get_sales_report",
        "reports",
        "/reports/sales",
        "GET",
        "list",
        "Get WooCommerce sales report",
        "reports",
    ),
    _wc(
        "wc_get_top_sellers_report",
        "reports",
        "/reports/top_sellers",
        "GET",
        "list",
        "Get WooCommerce top sellers report",
        "reports",
    ),
    _wc(
        "wc_get_coupons_totals_report",
        "reports",
        "/reports/coupons/totals",
        "GET",
        "list",
        "Get WooCommerce coupons totals report",
        "reports",
    ),
    _wc(
        "wc_get_customers_totals_report",
        "reports",
        "/reports/customers/totals",
        "GET",
        "list",
        "Get WooCommerce customers totals report",
        "reports",
    ),
    _wc(
        "wc_get_orders_totals_report",
        "reports",
        "/reports/orders/totals",
        "GET",
        "list",
        "Get WooCommerce orders totals report",
        "reports",
    ),
    _wc(
        "wc_get_products_totals_report",
        "reports",
        "/reports/products/totals",
        "GET",
        "list",
        "Get WooCommerce products totals report",
        "reports",
    ),
    _wc(
        "wc_get_reviews_totals_report",
        "reports",
        "/reports/reviews/totals",
        "GET",
        "list",
        "Get WooCommerce reviews totals report",
        "reports",
    ),
    # Taxes
    _wc("wc_list_taxes", "taxes", "/taxes", "GET", "list", "List WooCommerce tax rates", "taxes"),
    _wc(
        "wc_create_tax", "taxes", "/taxes", "POST", "create", "Create WooCommerce tax rate", "taxes"
    ),
    _wc(
        "wc_get_tax", "taxes", "/taxes/{id}", "GET", "get", "Get WooCommerce tax rate", "taxes", _ID
    ),
    _wc(
        "wc_update_tax",
        "taxes",
        "/taxes/{id}",
        "PUT",
        "update",
        "Update WooCommerce tax rate",
        "taxes",
        _ID,
    ),
    _wc(
        "wc_batch_taxes",
        "taxes",
        "/taxes/batch",
        "POST",
        "batch",
        "Batch create or update WooCommerce tax rates",
        "taxes",
    ),
    # Tax classes
    _wc(
        "wc_list_tax_classes",
        "tax_classes",
        "/taxes/classes",
        "GET",
        "list",
        "List WooCommerce tax classes",
        "tax-classes",
    ),
    _wc(
        "wc_create_tax_class",
        "tax_classes",
        "/taxes/classes",
        "POST",
        "create",
        "Create WooCommerce tax class",
        "tax-classes",
    ),
    # Webhooks are configured by hand in WooCommerce; see the Setup Guide. The
    # routes stay visible in coverage as webhook_administration_excluded.
    # Settings and setting options
    _wc(
        "wc_list_setting_groups",
        "settings",
        _PATH_SETTINGS,
        "GET",
        "list",
        "List WooCommerce setting groups",
        "settings",
    ),
    _wc(
        "wc_list_setting_options",
        "setting_options",
        "/settings/{group_id}",
        "GET",
        "list",
        "List WooCommerce setting options",
        "setting-options",
        (("group_id", "slug"),),
    ),
    _wc(
        "wc_get_setting_option",
        "setting_options",
        "/settings/{group_id}/{id}",
        "GET",
        "get",
        "Get WooCommerce setting option",
        "setting-options",
        (("group_id", "slug"), ("id", "slug")),
    ),
    _wc(
        "wc_update_setting_option",
        "setting_options",
        "/settings/{group_id}/{id}",
        "PUT",
        "update",
        "Update WooCommerce setting option",
        "setting-options",
        (("group_id", "slug"), ("id", "slug")),
    ),
    _wc(
        "wc_batch_setting_options",
        "setting_options",
        "/settings/{group_id}/batch",
        "POST",
        "batch",
        "Batch update WooCommerce setting options",
        "setting-options",
        (("group_id", "slug"),),
    ),
    # Payment gateways
    _wc(
        "wc_list_payment_gateways",
        "payment_gateways",
        "/payment_gateways",
        "GET",
        "list",
        "List WooCommerce payment gateways",
        "payment-gateways",
    ),
    _wc(
        "wc_get_payment_gateway",
        "payment_gateways",
        "/payment_gateways/{id}",
        "GET",
        "get",
        "Get WooCommerce payment gateway",
        "payment-gateways",
        (("id", "slug"),),
    ),
    _wc(
        "wc_update_payment_gateway",
        "payment_gateways",
        "/payment_gateways/{id}",
        "PUT",
        "update",
        "Update WooCommerce payment gateway",
        "payment-gateways",
        (("id", "slug"),),
    ),
    # Shipping zones
    _wc(
        "wc_list_shipping_zones",
        "shipping_zones",
        "/shipping/zones",
        "GET",
        "list",
        "List WooCommerce shipping zones",
        "shipping-zones",
    ),
    _wc(
        "wc_create_shipping_zone",
        "shipping_zones",
        "/shipping/zones",
        "POST",
        "create",
        "Create WooCommerce shipping zone",
        "shipping-zones",
    ),
    _wc(
        "wc_get_shipping_zone",
        "shipping_zones",
        "/shipping/zones/{id}",
        "GET",
        "get",
        "Get WooCommerce shipping zone",
        "shipping-zones",
        _ID,
    ),
    _wc(
        "wc_update_shipping_zone",
        "shipping_zones",
        "/shipping/zones/{id}",
        "PUT",
        "update",
        "Update WooCommerce shipping zone",
        "shipping-zones",
        _ID,
    ),
    # Shipping zone locations
    _wc(
        "wc_list_shipping_zone_locations",
        "shipping_zone_locations",
        "/shipping/zones/{id}/locations",
        "GET",
        "list",
        "List WooCommerce shipping zone locations",
        "shipping-zone-locations",
        _ID,
    ),
    _wc(
        "wc_update_shipping_zone_locations",
        "shipping_zone_locations",
        "/shipping/zones/{id}/locations",
        "PUT",
        "update",
        "Update WooCommerce shipping zone locations",
        "shipping-zone-locations",
        _ID,
    ),
    # Shipping zone methods
    _wc(
        "wc_list_shipping_zone_methods",
        "shipping_zone_methods",
        "/shipping/zones/{zone_id}/methods",
        "GET",
        "list",
        "List WooCommerce shipping zone methods",
        "shipping-zone-methods",
        (("zone_id", "integer"),),
    ),
    _wc(
        "wc_create_shipping_zone_method",
        "shipping_zone_methods",
        "/shipping/zones/{zone_id}/methods",
        "POST",
        "create",
        "Create WooCommerce shipping zone method",
        "shipping-zone-methods",
        (("zone_id", "integer"),),
    ),
    _wc(
        "wc_get_shipping_zone_method",
        "shipping_zone_methods",
        "/shipping/zones/{zone_id}/methods/{id}",
        "GET",
        "get",
        "Get WooCommerce shipping zone method",
        "shipping-zone-methods",
        (("zone_id", "integer"), ("id", "integer")),
    ),
    _wc(
        "wc_update_shipping_zone_method",
        "shipping_zone_methods",
        "/shipping/zones/{zone_id}/methods/{id}",
        "PUT",
        "update",
        "Update WooCommerce shipping zone method",
        "shipping-zone-methods",
        (("zone_id", "integer"), ("id", "integer")),
    ),
    # Shipping methods
    _wc(
        "wc_list_shipping_methods",
        "shipping_methods",
        "/shipping_methods",
        "GET",
        "list",
        "List WooCommerce shipping methods",
        "shipping-methods",
    ),
    _wc(
        "wc_get_shipping_method",
        "shipping_methods",
        "/shipping_methods/{id}",
        "GET",
        "get",
        "Get WooCommerce shipping method",
        "shipping-methods",
        (("id", "slug"),),
    ),
    # System status (read-only)
    _wc(
        "wc_get_system_status",
        "system_status",
        "/system_status",
        "GET",
        "get",
        "Get WooCommerce system status",
        "system-status",
    ),
    _wc(
        "wc_list_system_status_tools",
        "system_status_tools",
        "/system_status/tools",
        "GET",
        "list",
        "List WooCommerce system status tools",
        "system-status-tools",
    ),
    _wc(
        "wc_get_system_status_tool",
        "system_status_tools",
        "/system_status/tools/{id}",
        "GET",
        "get",
        "Get WooCommerce system status tool",
        "system-status-tools",
        (("id", "slug"),),
    ),
    # Data
    _wc(
        "wc_list_data_resources",
        "data",
        "/data",
        "GET",
        "list",
        "List WooCommerce data resources",
        "data",
    ),
    _wc(
        "wc_list_continents",
        "data",
        "/data/continents",
        "GET",
        "list",
        "List WooCommerce continents",
        "data",
    ),
    _wc(
        "wc_get_continent",
        "data",
        "/data/continents/{location}",
        "GET",
        "get",
        "Get WooCommerce continent",
        "data",
        (("location", "slug"),),
    ),
    _wc(
        "wc_list_countries",
        "data",
        "/data/countries",
        "GET",
        "list",
        "List WooCommerce countries",
        "data",
    ),
    _wc(
        "wc_get_country",
        "data",
        "/data/countries/{location}",
        "GET",
        "get",
        "Get WooCommerce country",
        "data",
        (("location", "slug"),),
    ),
    _wc(
        "wc_list_currencies",
        "data",
        "/data/currencies",
        "GET",
        "list",
        "List WooCommerce currencies",
        "data",
    ),
    _wc(
        "wc_get_currency",
        "data",
        "/data/currencies/{currency}",
        "GET",
        "get",
        "Get WooCommerce currency",
        "data",
        (("currency", "slug"),),
    ),
    _wc(
        "wc_get_current_currency",
        "data",
        "/data/currencies/current",
        "GET",
        "get",
        "Get the current WooCommerce currency",
        "data",
    ),
)

REST_OPERATIONS: tuple[Operation, ...] = WORDPRESS_OPERATIONS + WOOCOMMERCE_OPERATIONS
REST_OPERATIONS_BY_ID: dict[str, Operation] = {row.operation_id: row for row in REST_OPERATIONS}

TEST_CONNECTION_OPERATION_ID = "test_connection"

#: Runs before the connection form saves. The platform's secret-ref validator
#: executes only `required` and `additionalProperties`, so the `dependentRequired`
#: pairing rule and the https-only rule are declared but never enforced at save.
#: This operation enforces them from inside the extension, without reaching the
#: network and without ever receiving a secret value.
VALIDATE_SETTINGS_OPERATION_ID = "validate_connection_settings"
OPERATION_IDS: frozenset[str] = frozenset(REST_OPERATIONS_BY_ID) | {
    TEST_CONNECTION_OPERATION_ID,
    VALIDATE_SETTINGS_OPERATION_ID,
}


def operation(operation_id: Any) -> Operation | None:
    """Return the declared operation, or ``None`` when it is not in the registry."""
    if not isinstance(operation_id, str):
        return None
    return REST_OPERATIONS_BY_ID.get(operation_id.strip())


__all__ = [
    "EFFECT_SHAPES",
    "OPERATION_IDS",
    "PATH_PARAM_KINDS",
    "READ_SHAPES",
    "REST_OPERATIONS",
    "REST_OPERATIONS_BY_ID",
    "SHAPES",
    "SUPPORTED_METHODS",
    "SUPPORTED_NAMESPACES",
    "TEST_CONNECTION_OPERATION_ID",
    "WOOCOMMERCE",
    "WOOCOMMERCE_NAMESPACE",
    "WOOCOMMERCE_OPERATIONS",
    "WORDPRESS",
    "WORDPRESS_NAMESPACE",
    "WORDPRESS_OPERATIONS",
    "Operation",
    "operation",
]
